name: octave
channels:
  - conda-forge
  - defaults

dependencies:
  # Core
  - python=3.12
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - pillow
  - requests
  - tqdm
  - h5py
  - shapely
  - cartopy
  - pyproj
  - scikit-learn
  - sympy
  - networkx

  # Jupyter + tools
  - ipykernel
  - jupyter_core
  - jupyter_client

  # Octave + Jupyter kernel
  - octave=8.*       # pulls required libs automatically
  - gnuplot
  - graphicsmagick

  # PyTorch (CPU only)
  - pytorch=2.3.0

  # Other useful dependencies
  - pyyaml
  - typing_extensions
  - click

  - pip:
      - oct2py==4.0.6
      - octave-kernel==0.35.1
      - corner==2.2.2
      - glasflow==0.3.1
      - nessai==0.12.0
      - plotly==5.19.0
      - kaleido==0.2.1
      - colour==0.1.5
      - ipython
      - psutil
      - fsspec
      - torch==2.2.2      # your pip-installed CPU torch build
      - tenacity

variables:
  PYDEVD_DISABLE_FILE_VALIDATION: '1'
